console.log("**********  RESULT  **********");
console.log("Name - Malhar Rahangdale");
console.log("School - School of Scholars,Nagpur");
console.log("Grade - 10th");
console.log("Section - A");
console.log("Roll no. - 13");
console.log("Education - Science");
console.log("      ");
console.log("      ");
console.log("     ");
console.log("**********  Marks Obtained  **********");
console.log("Physics         Biology         Maths");
console.log("   58              60             75");
